-- Migration 034 (UPGRADE): Loading Vouchers schema (سندات التحميل).
--
-- Creates the standalone ``loading_vouchers`` table and its supporting objects
-- (numbering sequence, number-format function, unique/report indexes, updated_at
-- trigger). Does NOT touch, drop, or alter any existing table or data. All
-- existing tables (customers, products, companies, receipt_vouchers,
-- production_orders, ...) and their rows are preserved. If a ``loading_vouchers``
-- table already exists this migration is additive and idempotent — every
-- statement uses CREATE ... IF NOT EXISTS / CREATE OR REPLACE / a forward-only
-- re-seed, so no existing voucher data is deleted or modified.
--
-- WHAT / WHY
--   A Loading Voucher is a simple single-item logistics document: one header row
--   records that a quantity (in tons) of one item was loaded for a customer onto a
--   vehicle driven by a named driver at a given date/time. There is NO detail-line
--   table, no company link, no document-status / approval workflow and no inventory
--   posting in this version. Deletes are hard deletes.
--
--   id                     : PostgreSQL IDENTITY (sequence-backed) primary key.
--                            Generated by PostgreSQL; never MAX(id)+1.
--   voucher_number         : user-facing document number. Automatic values come
--                            from the sequence ``loading_voucher_number_seq``
--                            (first nextval = 1, rendered as LV-001, then LV-002,
--                            ...). Atomic and concurrency-safe; the UNIQUE index is
--                            the final guard. Stays editable — a user may store a
--                            manual number and the numbering re-seeds the sequence
--                            past any manual LV-<n>. Never MAX(voucher_number)+1.
--                            The number is formatted through
--                            loading_voucher_format_number() (min 3 digits, grows
--                            past 999 -> LV-1000; a fixed FM000 mask was avoided as
--                            it overflows to '###').
--   voucher_date           : date, defaults to CURRENT_DATE for a new voucher.
--   voucher_time           : time, defaults to localtime (separate from the date,
--                            mirroring the cashier-invoice convention).
--   Every business field below is OPTIONAL (v1): customer, driver, vehicle, item,
--   quantity and notes may all be left blank. The two FKs stay enforced when a
--   value is supplied (an FK column accepts NULL).
--   customer_id            : optional, RESTRICT FK -> customers(customer_id).
--   customer_name_snapshot : customer name frozen at save time (optional).
--   driver_name            : optional free text (no drivers master exists yet).
--   vehicle_number         : optional free text (no vehicles master exists yet).
--   weight_before_loading /
--   weight_after_loading   : optional FREE TEXT (varchar(50)) vehicle weighbridge
--                            readings before / after loading — stored literally so a
--                            typed unit ("500k", "500 كجم") is preserved.
--   product_id             : optional, RESTRICT FK -> products(id).
--   item_code_snapshot /
--   item_name_snapshot /
--   unit_snapshot          : item code/name/unit frozen at save time (optional).
--   quantity_tons          : numeric(18,3), optional; CHECK allows NULL else > 0
--                            (never FLOAT/REAL).
--   notes                  : optional Unicode text (Arabic / English).
--   created_at             : row creation timestamp (timestamptz, DEFAULT now()).
--   updated_at             : maintained by the BEFORE UPDATE trigger.
--   created_by / updated_by: nullable FKs -> app_users(id), ON DELETE SET NULL.
--
-- Mirrors app/models/loading_voucher.py (LOADING_VOUCHERS_SCHEMA_SQL) and the
-- public.loading_vouchers block in app/database/schema/full_schema.sql. Reverse
-- with 034_downgrade_loading_vouchers_schema.sql.
--
-- Safe to run repeatedly: every statement is idempotent and nothing is dropped,
-- reset, or deleted.

BEGIN;

CREATE SEQUENCE IF NOT EXISTS loading_voucher_number_seq AS bigint MINVALUE 1;

-- Formatter for the voucher number: 'LV-' + zero-padded sequence value with a
-- MINIMUM of 3 digits that GROWS naturally (LV-001 ... LV-999, LV-1000, ...).
-- Identical to Python format_number(). A fixed to_char mask (FM000) was avoided on
-- purpose: it overflows to '###' once the value exceeds 3 digits.
CREATE OR REPLACE FUNCTION loading_voucher_format_number(seq_value bigint)
    RETURNS text LANGUAGE sql IMMUTABLE AS
$$ SELECT 'LV-' || lpad(seq_value::text, GREATEST(3, length(seq_value::text)), '0') $$;

CREATE TABLE IF NOT EXISTS loading_vouchers (
    id                     integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    voucher_number         varchar(30) NOT NULL
                             DEFAULT loading_voucher_format_number(
                                         nextval('loading_voucher_number_seq')),
    voucher_date           date NOT NULL DEFAULT CURRENT_DATE,
    voucher_time           time NOT NULL DEFAULT localtime,
    customer_id            integer,
    customer_name_snapshot varchar(150),
    driver_name            varchar(150),
    vehicle_number         varchar(50),
    weight_before_loading  varchar(50),
    weight_after_loading   varchar(50),
    product_id             integer,
    item_code_snapshot     integer,
    item_name_snapshot     varchar(200),
    unit_snapshot          varchar(50) NOT NULL DEFAULT '',
    quantity_tons          numeric(18, 3),
    notes                  text,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    created_by             integer,
    updated_by             integer,
    -- Every business field is optional (v1). Only voucher_number (auto) is guarded
    -- not-blank; a supplied quantity must be positive, but NULL is allowed.
    CONSTRAINT ck_loading_vouchers_quantity_positive
        CHECK (quantity_tons IS NULL OR quantity_tons > 0),
    CONSTRAINT ck_loading_vouchers_voucher_number_not_blank
        CHECK (char_length(btrim(voucher_number)) > 0),
    CONSTRAINT fk_loading_vouchers_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_loading_vouchers_product
        FOREIGN KEY (product_id) REFERENCES products (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_loading_vouchers_created_by
        FOREIGN KEY (created_by) REFERENCES app_users (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_loading_vouchers_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER SEQUENCE loading_voucher_number_seq OWNED BY loading_vouchers.voucher_number;

-- Forward-only re-seed (idempotent). On a fresh table this is a no-op, so the
-- first nextval() stays 1 (LV-001). On a re-run over existing LV-<n> data it
-- advances the sequence past the greatest existing <n>; it never regresses.
DO $$
DECLARE
    max_existing bigint;
    seq_last     bigint;
BEGIN
    SELECT COALESCE(
             MAX(CAST(substring(voucher_number FROM '^LV-([0-9]+)$') AS bigint)),
             0)
      INTO max_existing
      FROM loading_vouchers
     WHERE voucher_number ~ '^LV-[0-9]+$';

    SELECT last_value INTO seq_last FROM loading_voucher_number_seq;

    IF max_existing > seq_last THEN
        PERFORM setval('loading_voucher_number_seq', max_existing, true);
    END IF;
END $$;

-- Unique voucher number (final guard + exact/prefix lookup path).
CREATE UNIQUE INDEX IF NOT EXISTS uq_loading_vouchers_voucher_number
    ON loading_vouchers (voucher_number);

-- Report / search indexes.
CREATE INDEX IF NOT EXISTS idx_loading_vouchers_voucher_date
    ON loading_vouchers (voucher_date);
CREATE INDEX IF NOT EXISTS idx_loading_vouchers_customer_id
    ON loading_vouchers (customer_id);
CREATE INDEX IF NOT EXISTS idx_loading_vouchers_product_id
    ON loading_vouchers (product_id);

-- Keep updated_at accurate on every UPDATE (dedicated function name avoids
-- clashing with the other modules' trigger functions).
CREATE OR REPLACE FUNCTION loading_voucher_set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_loading_vouchers_set_updated_at ON loading_vouchers;
CREATE TRIGGER trg_loading_vouchers_set_updated_at
    BEFORE UPDATE ON loading_vouchers
    FOR EACH ROW EXECUTE FUNCTION loading_voucher_set_updated_at();

COMMIT;

-- Post-conditions (informational): table shape + current row count.
SELECT 'loading_vouchers' AS table_created,
       (SELECT COUNT(*) FROM loading_vouchers) AS row_count;
